### PR TITLE
remove wiki, subreddit, irc links, add twitter

### PR DESCRIPTION
**Pull request by johnathanhowell**

### CODE REVIEW

**Comment by johnathanhowell** [comment]
rebased, now running on staging

**Comment by DavidVorick** [comment]
Couple more things to remove:

+ links to 'docs' in the footer
+ links to 'docs' in 'Discover more'
+ link to whitepaper in 'Discover more'
+ switch all of the roadmap links to point to our roadmap Trello (but leave the legacy roadmap page so we don't break any links)

**Comment by DavidVorick** [comment]
https://trello.com/b/Io1dDyuI/sia-public-roadmap

**Comment by DavidVorick** [comment]
LGTM

**Pull request merged**
