### PR TITLE
Update homepage

### PR DESCRIPTION
**Pull request by VoidingWarranties**
The main goal of this PR is to better answer the question "what is Sia?" The current homepage does not answer that question very well, especially for a newcomer who is hearing about Sia for the first time.

The intro video has been moved from the about page to the homepage, and the download button has been changed to a Get Started button.

screen shot 2016-10-23 at 23 31 47

### CODE REVIEW

**Comment by DavidVorick** [comment]
"Cheap" => "Competitive"

I don't like the new giant header, I think we should come up with different wording. Maybe video title should be 'Introductory Video'. At first I didn't like that the video was so far down the page, but I think it has grown on me - makes sense that people would see the text first, because it's a lot more concise.

While we're at it, 'Total Contract Size' should be replaced with 'Total Contract Cost', though the name should probably be changed to something like 'Economic Throughput'. 'Total Siacoins' should also be replaced, probably to 'Current Block Height'.

I'm also wondering if it wouldn't be better to direct people to join our slack instead of ask them to join our mailing list. We don't use the mailing list (I will be sending out an email for v1.0.3 though).

**Comment by DavidVorick** [comment]
"often well below..." -> should probably say something like "meaning that the platform is [hyper competitive](https://i.imgur.com/Y4kqmxx.png)"

**Comment by DavidVorick** [comment]
I'm also noticing the 'Get Siacoin' button at the top-right of the header. Perhaps that should also be a 'Get Started' button, and then we make sure that the Get-Started page has links to the 'Get Siacoin' page.

**Comment by johnathanhowell** [comment]
Total Contract Size should probably be removed since it's not a metric that we're tracking anymore.

**Comment by VoidingWarranties** [comment]
Updated the subheader to "What is Sia?".

> "Cheap" => "Competitive"

Updated to "Competitively Priced"

> I don't like the new giant header, I think we should come up with different wording.

What giant header are you referring to?

> Maybe video title should be 'Introductory Video'.

Updated to "How Sia Works". No need to say it's a video.

> While we're at it, 'Total Contract Size' should be replaced with 'Total Contract Cost', though the name should probably be changed to something like 'Economic Throughput'. 'Total Siacoins' should also be replaced, probably to 'Current Block Height'.

The javascript in this repo is the minimized version. Do we have the original source? Otherwise it's too difficult to edit easily.

> I'm also wondering if it wouldn't be better to direct people to join our slack instead of ask them to join our mailing list. We don't use the mailing list (I will be sending out an email for v1.0.3 though).

Our mailing list is underutilized for sure. I think there are lots of links to the Slack throughout the rest of the website that linking to the Slack instead of the mailing list isn't necessary.

> "often well below..." -> should probably say something like "meaning that the platform is hyper competitive"

Added link to comparison table, but with slightly different working. Let me know what you think.

> I'm also noticing the 'Get Siacoin' button at the top-right of the header. Perhaps that should also be a 'Get Started' button, and then we make sure that the Get-Started page has links to the 'Get Siacoin' page.

Agreed, done.

Here's an updated screenshot
screen shot 2016-10-24 at 23 07 48

**Pull request merged**
