### PR TITLE
update getting started page with getting started guide, change ordering

### PR DESCRIPTION
**Pull request by johnathanhowell**
This PR changes the get started page, adding a link to the new Getting Started guide, and changing the ordering so that 'store' appears first.

Changes are live at http://staging.sia.tech/get-started/

### CODE REVIEW

**Comment by DavidVorick** [comment]
it's not clear that the link to the guide is actually a link, and it doesn't really fit in well with the step-by-step.

Maybe instead of a 4, you can have an empty bullet point, and a "full guide here" or "full guide **here**"

**Comment by DavidVorick** [comment]
or maybe we can copy the "Follow the **hosting guide**" but  for renters

**Comment by johnathanhowell** [comment]
Updated this PR per your recommendations, it now matches the hosting page and says '(4) Follow the storage guide'. Changes are live on http://staging.sia.tech/get-started/

**Comment by johnathanhowell** [comment]
I also updated the links to the hosting and api quickstart guides, since the blog has been migrated.

**Pull request merged**
