### PR TITLE
Add /brand page

### PR DESCRIPTION
**Pull request by VoidingWarranties**
screen shot 2016-11-09 at 18 37 14

### CODE REVIEW

**Comment by DavidVorick** [comment]
Needs the color palate and font set as well.

For blurbs:

"Sia is a decentralized cloud storage platform, serving an API that allows you to upload and download files. Files are encrypted and spread across dozens of nodes on the network, such that there's no single point of failure. On Sia, you control the data. Safer, more secure, more private - a better cloud."

**Comment by DavidVorick** [comment]
I think it might look nicer if each of the images had more padding/spacing as well.

**Comment by VoidingWarranties** [comment]
I'll add the blurbs.

Who is the audience of the brand page? I've never seen a company brand page with a color and font set.

**Comment by DavidVorick** [comment]
The audience is anyone who is looking to create content for Sia that fits in with the official Sia apps. I get enough requests for it from community members that I think it's justified to go in the brand page.

**Comment by DavidVorick** [comment]
But I think it would also help situations like the CoinTelegraph image which had red coloring on the Sia beaker - the red really didn't fit in with our typical branding, and perhaps if there had been a color guide they would have picked something more appropriate.

**Pull request merged**
